tap "homebrew/bundle"
tap "aws/tap"
tap "heroku/brew"

cask "iterm2"
brew "autojump"
brew "zsh"
brew "zsh-completions"
brew "gsettings-desktop-schemas"
brew "libavif"

# Networking
brew "putty"
brew "curl"
brew "openssl@3"
cask "ssh-tunnel-manager"
cask "tunnelblick"
cask "okta-advanced-server-access"
brew "speedtest-cli"
brew "bitwarden-cli"
brew "ca-certificates"
brew "wget"

# Build
brew "cmake"
brew "ansible"

# Git
brew "git"
brew "git-secrets"
brew "pre-commit"
# cask "github"

# dotnet
brew "dotnet"
# cask "dotnet-sdk"
# cask "mono-mdk"

# Java
brew "jenv"
# brew "openjdk@8"
brew "openjdk@11"
brew "openjdk@17"
brew "openjdk@21"
brew "gradle"
brew "maven"

# Node
brew "nodenv"
brew "node@20"
brew "node@22"
brew "yarn"
brew "mockserver"
brew "gulp-cli"

# FE Frameworks
brew "angular-cli"

# Python
brew "python"
brew "virtualenv"
brew "autoenv"

# Go
brew "go"

# Clojure
brew "leiningen"
brew "guile"	

# Scala
brew "coursier"
brew "scala"

# Docker
# brew "docker"
# brew "docker-compose"
# brew "colima"
# brew "podman"
# brew "lima"

# Terraform
brew "terraform-docs"
brew "tfenv"
	
# Database
brew "postgresql@17"
brew "mongodb-atlas-cli"
brew "mysql"
brew "sqlite"

# Ruby
brew "rbenv"
brew "ruby-install"
brew "ruby-build"

# Rust
brew "rust"

# Kubernetes
brew "kubernetes-cli"
brew "kubectx"
brew "kube-linter"	
# brew "Azure/kubelogin/kubelogin"
brew "k9s"
brew "minikube"
brew "helm"	

# Shell tools
brew "jq"
brew "yq"
brew "shellcheck"
brew "parallel"
brew "watch"

# Documentation
brew "asciidoc"
brew "pandoc"
brew "adr-tools"

# Drawing
# cask "processing"
brew "graphviz"
brew "plantuml"
brew "d2"

# Hardware
# cask "qmk-toolbox"

# AWS
brew "awscli"
brew "awsume"	
brew "aws-sam-cli"	

# Azure
brew "azure-cli"	

# Heroku
brew "heroku"

# Circle CI
brew "circleci"	

# Applications
cask "spotify"
cask "bitwarden"
cask "firefox"
cask "zoom"
cask "raspberry-pi-imager"
cask "dbeaver-community"
cask "signal"
cask "insomnia"
cask "intellij-idea-ce"
cask "visual-studio-code"
cask "karabiner-elements"
cask "notion"
# cask "whatsapp"
# cask "slack"
# cask "microsoft-office"
# cask "microsoft-teams"