tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "aws/tap"

brew "zsh"
brew "zsh-completions"

# Networking
brew "putty"
brew "curl"
brew "openssl@1.1"
cask "ssh-tunnel-manager"
cask "tunnelblick"
cask "okta"
brew "speedtest"
brew "bitwarden-cli"
brew "ca-certificates"
brew "wget"

# Build
brew "cmake"
brew "ansible"
brew "packer"

# Git
brew "git"
brew "git-secrets"
brew "pre-commit"

# dotnet
brew "dotnet"
# cask "dotnet-sdk"
cask "mono-mdk"

# Java
brew "jenv"
brew "openjdk@8"
brew "openjdk@11"
brew "openjdk@17"
brew "openjdk@20"
brew "gradle"
brew "maven"

# Node
brew "nodenv"
brew "node@14"
brew "node@16"
brew "yarn"
brew "mockserver"

# Python
brew "python"
brew "virtualenv"

# Go
brew "go"

# Clojure
brew "leiningen"
brew "guile"	

# Docker
brew "docker-compose"
brew "colima"
brew "podman"
brew "lima"

# Terraform
brew "tfenv"
brew "terraform"
brew "terraform-docs"
	
# Database
brew "postgresql"
brew "mongodb-community"
brew "mysql"
brew "sqlite"

# Ruby
brew "rbenv"
brew "ruby-install"

# Kubernetes
brew "kubernetes-cli"
brew "kubectx"
brew "kubelogin"	
brew "k9s"
brew "minikube"
brew "helm"	

# Tools
brew "jq"
brew "yq"
brew "shellcheck"
brew "parallel"
brew "graphviz"
brew "watch"
brew "adr-tools"
brew "plantuml"

# AWS
brew "awscli"
brew "awsume"	
brew "aws-sam-cli"	

# Azure
brew "azure-cli"	

# Heroku
brew "heroku"

# Circle CI
brew "circleci"	

# Applications
cask "slack"
cask "spotify"
cask "bitwarden"
cask "microsoft-office"
cask "microsoft-teams"
cask "firefox"
cask "whatsapp"
cask "zoom"
cask "raspberry-pi-imager"
cask "dbeaver-community"
cask "signal"
cask "insomnia"
cask "visual-studio-code"
# cask "intellij-idea-ce"