# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: de883f771311898d30a92f6fb2ddba3ca0ab31dc
    hooks:
      - id: markdownlint
        name: Markdown linter
        args: [-f]
  - repo: local
    hooks:
      - id: talisman-precommit
        name: talisman
        entry: bash -c 'if [ -n "${TALISMAN_HOME:-}" ]; then ${TALISMAN_HOME}/talisman_hook_script pre-commit; else echo "TALISMAN does not exist. Consider installing from https://github.com/thoughtworks/talisman . If you already have talisman installed, please ensure TALISMAN_HOME variable is set to where talisman_hook_script resides, for example, TALISMAN_HOME=${HOME}/.talisman/bin"; fi'
        language: system
        pass_filenames: false
        types: [text]
        verbose: true
  - repo: local
    hooks:
      - id: terraform
        name: Format terraform
        entry: ./scripts/terraform_fmt.sh
        language: script
  - repo: local
    hooks:
      - id: linting
        name: Lint code
        entry: ./scripts/code_linter.sh
        language: script
  - repo: local
    hooks:
      - id: test
        name: Install and test
        entry: ./scripts/install_and_test.sh
        language: script
